name : autodoc-generation
# triggers
on :
    push:
        branches: Sphinx
    pull_request:
        branches: Sphinx

jobs :
    build :
        runs-on : ubuntu-latest
        steps :
        - uses : actions/checkout@Sphinx
        - uses : actions/setup-python@v2
          with :
            python-version : '3.9'
        - name : Install dependencies
          run : |
             python -m pip install -- upgrade pip
             pip install -r requirements.txt
        - name : Create virtual environment
          run : python -m venv venv && source venv/bin/activate && pip
      install -r requirements.txt
        - name : Create documentation
          run : cd docs && source ../venv/bin/activate && python ../venv/bin
      /sphinx-apidoc -f -d 8 -o . .. && make html && cd ..
        - name : Publish documentation to gh-pages branch
          run : |
            git config user . name 'github - actions [ bot ]' && git config user .
      email 'github-actions[bot]@users.noreply.github.com'
            mkdocs gh-deploy --config-file docs/mkdocs.yml -- force
